## Libraries

In [ ]:
! pip install numpy
! pip install pandas
! pip install scikit-learn

In [8]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from IPython.display import display

## 1.3.1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами.

In [3]:
_matrix = np.zeros([8,8])
_matrix[::2, ::2] = 1
_matrix[1::2, 1::2] = 1
display(_matrix)

_matrix = np.ones([8,8])
_matrix[::2, ::2] = 0
_matrix[1::2, 1::2] = 0
display(_matrix)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## 1.3.2
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания 
необходимо использовать функцию arrange.

In [ ]:
_matrix = np.array([np.arange(5) for _ in range(5)])

_matrix

## 1.3.3
Создать массив 3x3x3 со случайными значениями. 

In [ ]:
np.random.rand(3,3,3)

## 1.3.4
Создать матрицу с 0 внутри, и 1 на границах. 

In [7]:
_matrix = np.ones((10,10))
_matrix[1:-1, 1:-1] = 0
display(_matrix)

_matrix = np.ones((10,10))
_matrix[2:-2, 2:-2] = 0
display(_matrix)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 1.3.5
Создайте массив и отсортируйте его по убыванию.

In [ ]:
np.sort(np.random.rand(10))[::-1]

## 1.3.6
Создайте матрицу, выведите ее форму, размер и размерность. 

In [ ]:
_matrix = np.random.rand(3,3,3)

_matrix.shape, _matrix.size, _matrix.ndim

## 2.3.1
Найдитн евклидово расстояние между двумя Series (точками) a и b, не 
используя встроенную формулу.

In [ ]:
_series1 = pd.Series([2, 4, 6, 8])
_series2 = pd.Series([1, 3, 5, 7])

# Решение 
sum((_series2 - _series1) ** 2) ** 0.5

## 2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данных можно найти 
здесь: https://github.com/akmand/datasets). 

In [ ]:
_series = pd.read_csv("./Datasheets.csv", sep='|')
_series

## 2.3.3
Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
_series = pd.read_csv("./Datasheets.csv", sep='|')

In [ ]:
_series.head(2)

In [ ]:
_series.tail(3)

In [ ]:
_series.shape

In [ ]:
_series.describe()

In [ ]:
_series.iloc[1:4]

In [ ]:
_series[_series["role"] == "HQ"].head(2)

## 3.3.2
Загрузить фрейм данных по ссылке: 
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. 
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
_series = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
_series

In [ ]:
_normalized_series = _series
_normalized_series[['sepal_length_cm']] = preprocessing.MinMaxScaler().fit_transform(_series[['sepal_length_cm']])
_normalized_series[['sepal_width_cm']] = preprocessing.MaxAbsScaler().fit_transform(_series[['sepal_width_cm']])


_series

## extra

### 2.2.6

In [39]:
# df = pd.read_csv("https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv")
df = pd.read_csv("./Datasheets.csv",sep='|')
# display(df)
display(df.loc[1:5, ["name", "role"]])
display(df.iloc[1:5, [1, 5]])

name           role
1             Venerable Contemptor Dreadnought         Elites
2                        Venerable Land Raider  Heavy Support
3                              Trajann Valoris             HQ
4                               Shield-Captain             HQ
5  Shield-Captain in Allarus Terminator Armour             HQ

name           role
1  Venerable Contemptor Dreadnought         Elites
2             Venerable Land Raider  Heavy Support
3                   Trajann Valoris             HQ
4                    Shield-Captain             HQ

### 2.2.7

In [42]:
df = pd.read_csv("./Datasheets.csv",sep='|')
# display(df)
display(df[(df["role"] == "Flyers") & (df["faction_id"] == 'AdM')])

id                      name  \
61  2085   Archaeopter Transvector   
62  2086  Archaeopter Stratoraptor   
63  2087      Archaeopter Fusilave   

                                                 link faction_id  source_id  \
61  https://wahapedia.ru/wh40k9ed/factions/adeptus...        AdM       15.0   
62  https://wahapedia.ru/wh40k9ed/factions/adeptus...        AdM       15.0   
63  https://wahapedia.ru/wh40k9ed/factions/adeptus...        AdM       15.0   

      role                                   unit_composition  \
61  Flyers  An Archaeopter Transvector is equipped with: 2...   
62  Flyers  An Archaeopter Stratoraptor is equipped with: ...   
63  Flyers  An Archaeopter Fusilave is equipped with: 4 co...   

                                            transport power_points priest  \
61  This model has a <a href="/wh40k9ed/the-rules/...            6    NaN   
62                                                NaN           10    NaN   
63                                                NaN            8    NaN   

   psyker  open_play_only  crusade_only  virtual  Cost  cost_per_unit  \
61    NaN           False         False    False   NaN          False   
62    NaN           False         False    False   NaN          False   
63    NaN           False         False    False   NaN          False   

    Unnamed: 16  
61          NaN  
62          NaN  
63          NaN