# Практика №2

## Операции над множествами. Свойства бинарных отношений. Замыкания отношений

Множества являются неопределяемыми понятиями и представляют собой неупорядоченную коллекцию уникальных элементов.
То есть, что два множества совпадают, если содержат одинаковые элементы.
Множества, состоящие из конечного числа элементов, называются конечными, в противном случае множества являются бесконечными. Конечное множество можно задать перечислением его элементов. Рассмотрим как можно работать с множествами средствами языка Python на примере конечных множеств.

### Способы задания множеств

перечисление элементов множества в фигурных скобках:

In [1]:
fruits = {"banana", "apple", "orange"}
print(fruits)
print(type(fruits))

{'orange', 'apple', 'banana'}
<class 'set'>


Единственное ограничение, что таким образом нельзя создать пустое множество. Вместо этого будет создан пустой словарь:

In [2]:
wrong_empty_set = {}
print(type(wrong_empty_set))

<class 'dict'>


Для создания пустого множества нужно непосредственно использовать set():

In [3]:
correct_empty_set = set()
print(type(correct_empty_set))

<class 'set'>


Множество можно задать с помощью set(), если передать в нее какой-либо объект, по которому можно проитерироваться 

In [4]:
fruits_set = set({"banana", "apple", "banana", "orange"})
print(fruits_set)
print(type(fruits_set))

{'orange', 'apple', 'banana'}
<class 'set'>


In [5]:
fruits_set_1 = set ({ "apple", "orange", "banana", })
print(fruits_set == fruits_set_1)

True


### Подмножество и надмножество

In [6]:
# Множество чисел Фибоначчи меньших 100
fibonacci_numbers = {0, 1, 2, 3, 34, 5, 8, 13, 21, 55, 89}

# Множество натуральных чисел меньших 100
natural_numbers = set(range(100))

# Множество чисел Фибоначчи является подмножеством множества 
# натуральных чисел
if fibonacci_numbers.issubset(natural_numbers):
    print("Подмножество!")

# В свою очередь множество натуральных чисел является
# надмножеством множества чисел Фибоначчи
if natural_numbers.issuperset(fibonacci_numbers):
    print("Надмножество!")

Подмножество!
Надмножество!


Пустое множество является подмножеством абсолютно любого множества.

In [7]:
empty = set()

# Методы issubset и issuperset могут принимать любой iterable-объект
print(
    empty.issubset(range(100))
    and empty.issubset(["red", "green", "blue"])
    and empty.issubset(set())
)

True


Само множество является подмножеством самого себя.

In [8]:
natural_numbers = set(range(100))

if natural_numbers.issubset(natural_numbers):
    print("Подмножество!")

Подмножество!


### Операции над множествами

Объединение множеств

In [9]:
my_fruits = {"apple", "orange"}
your_fruits = {"orange", "banana", "pear"}

# Для объединения множеств (типа set) можно использовать оператор `|`,

our_fruits = my_fruits | your_fruits
print(our_fruits)

{'orange', 'apple', 'banana', 'pear'}


In [10]:
# Также можно использовать ментод union.
# Отличие состоит в том, что метод union принимает не только
# объект типа set, а любой iterable-объект
you_fruit_list: list = list(your_fruits)
our_fruits: set = my_fruits.union(you_fruit_list)
print(our_fruits)

{'orange', 'apple', 'pear', 'banana'}


Добавление элементов в множество.
Добавление элементов в множество можно рассматривать как частный случай объединения множеств за тем исключением, что добавление элементов изменяет исходное множество, а не создает новый объект

In [11]:
colors = {"red", "green", "blue"}

# Метод add добаляет новый элемент в множество
colors.add("purple")
# Добавление элемента, который уже есть в множестве, не изменяет
# это множество
colors.add("red")
print(colors)

{'blue', 'purple', 'green', 'red'}


In [12]:
# Метод update принимает iterable-объект (список, словарь, генератор и т.п.)
# и добавляет все элементы в множество
numbers = {1, 2, 3}
numbers.update(i**2 for i in [1, 2, 3])
print(numbers)

{1, 2, 3, 4, 9}


### Свойства множеств 

К основным свойствам множеств, которые мы хотим проверять, относятся рефлексивность, антирефлексивность, симметричность, антисимметричность, транзитивность.
Сгенерируем произвольное бинарное отношение

In [13]:
import random
x=4
y=4
array = [[random.randint(0, 1) for i in range(x)] for j in range(y)]
array


[[0, 0, 1, 0], [0, 0, 1, 0], [0, 1, 0, 1], [1, 1, 1, 0]]

Проверим рефлексивность. Чтобы выявить наличие единиц на главной диагонали, сгенерируем единичную матрицу нужной размерности, и проверим включается ли она в исходное отношение. Но можно и напрямую проверить, что элементы с i=j в отношении равны 1


In [26]:
## ваш код
import random
MATRIXSIZE = 5

matrix = [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]

all(matrix[i][i] == 1 for i in range(MATRIXSIZE))

False

Для проверки антирефлексивности необходимо проверить, что что элементы с i=j в отношении равны 0


In [27]:
## ваш код
import random
MATRIXSIZE = 5

matrix = [[0, 1, 1, 1, 1],
          [1, 0, 1, 1, 1],
          [1, 1, 0, 1, 1],
          [1, 1, 1, 0, 1],
          [1, 1, 1, 1, 0]]

all(matrix[i][i] == 0 for i in range(MATRIXSIZE))

True

Для проверки симметричности нужно проверить, что если в отношении i,j-ый элемент равен 1, то и j,i-ый элемент тоже равен единице

In [28]:
## ваш код
import random
MATRIXSIZE = 5

matrix = [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 0, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]

all(
    matrix[i][j] == matrix[j][i] 
    for j in range(MATRIXSIZE) 
    for i in range(j))

False

Для проверки антисимметричности нужно проверить, что если в отношении i,j-ый элемент равен единице, то и j,i-ый элемент равен нулю

In [29]:
## ваш код
import random
MATRIXSIZE = 5

matrix = [[1, 1, 1, 1, 1],
          [0, 0, 1, 1, 1],
          [0, 0, 1, 1, 1],
          [0, 0, 0, 1, 1],
          [0, 0, 0, 0, 1]]

all(
    matrix[i][j] != matrix[j][i] 
    for j in range(MATRIXSIZE) 
    for i in range(j))

True

Для проверки транзитивности нужно проверить, что если i,j-ый и j,k-ый элементы принадлежат отношению, то и i,k-ый элемент тоже равен единице

In [30]:
## ваш код
import random
MATRIXSIZE = 5

matrix = [[1, 0, 1, 0, 1],
          [0, 1, 0, 1, 0],
          [1, 0, 1, 0, 1],
          [0, 1, 0, 1, 0],
          [1, 0, 1, 0, 1]]

all(
    not(matrix[i][j] and matrix[j][k]) or matrix[i][k]
    if i != j != k != i 
    else True

    for j in range(MATRIXSIZE) 
    for i in range(MATRIXSIZE) 
    for k in range(MATRIXSIZE))


False

### Множество всех подмножеств
Алгоритм Грея генерирует последовательность всех подмножеств п-элементного множества, причём каждое следующее подмножество получается из предыдущего удалением или добавлением в точности одного элемента.

In [19]:
## ваш код

### Транзитивное замыкание

Транзитивное замыкание бинарного отношения, представленного в виде бинарной матрицы, 
представляет собой объединение положительных степеней (всех) исходного отношения

In [20]:
import numpy as np
A = np.array([[0, 0, 1, 0], 
              [0, 0, 1, 1], 
              [1, 0, 0, 0], 
              [0, 0, 1, 0]])
print(A)

[[0 0 1 0]
 [0 0 1 1]
 [1 0 0 0]
 [0 0 1 0]]


Исходный алгоритм Уоршелла проще, поскольку он находит только транзитивное замыкание графа и не использует никакой информации о весах ребер. Алгоритм Флойда в основном является этим алгоритмом с дополнительными соображениями о таких весах. Алгоритм Флойда-Уоршалла решает проблему кратчайшего пути для всех пар. Соответственно, на вход алгоритма Флойда-Уоршалла нужно подавать взвешенноую матрицу бинарного отношения, в которой ненулевой элемент обозначает не только наличие отношения между i и j элементами, но и силу этой связи (выраженную положительным числом).

In [21]:
def warshall(G):
  W = G  
  n = len(G)
  for k in range(n):
    for i in range(n):
      for j in range(n):
        G[i, j] = G[i, j] or (G[i, k] and G[k, j])
  return W  

In [22]:
warshall(A)

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

Так как транзитивное замыкание показывает, что если есть путь из i-ой вершины в k-ую и из k-ой вершины в j-ую, то есть путь и из i-ой вершины в j-ую. Соответственно сама матрица отношения это пути дляны 1, если мы строим композицию RR, то в итоге получаем наличие пути, длины 2, а если выполняем обычное возведение в степень, то за счет сложения будем видеть количество путей, длина которых соответствует степени.

In [23]:
array_1 = ([[0, 0, 1, 0], [0, 0, 1, 1], [1, 0, 0, 0], [0, 0, 1, 0]])
np.linalg.matrix_power(array_1, 1) + np.linalg.matrix_power(array_1, 2) + np.linalg.matrix_power(array_1, 3)+np.linalg.matrix_power(array_1, 4)+np.linalg.matrix_power(array_1, 5)

array([[2, 0, 3, 0],
       [4, 0, 5, 1],
       [3, 0, 2, 0],
       [2, 0, 3, 0]])

Поэтому встает закономерный вопрос, какой путь из предложенных будет иметь наименьшую длину?
Ответ можно найти с помощью алгоритма Флойда-Уоршалла. Только зададим веса. Обратите внимание на нули, которые обозначают отсутствующие пути.

In [42]:
# ## ваша матрица
MATRIXSIZE = 5
MATRIXINT = 10
INF = 99999

dist = np.random.randint(MATRIXINT, size=(MATRIXSIZE, MATRIXSIZE))
for i in range(MATRIXSIZE):
    for j in range(MATRIXSIZE):
        if i == j: continue
        if dist.item(i, j) == 0:
            dist.itemset(i, j, INF)


for v in range(MATRIXSIZE): dist.itemset((v, v), 0)

print(dist)

for k in range(MATRIXSIZE):
    for i in range(MATRIXSIZE):
        for j in range(MATRIXSIZE):
            if (dist.item((i, k)) <= 0 or dist.item((k, j)) == 0): continue
            if dist.item((i, j)) > dist.item((i, k)) + dist.item((k, j)):
                dist.itemset((i, j), dist.item((i, k)) + dist.item((k, j)))


dist

[[    0 99999 99999     6     7]
 [    3     0     7     1 99999]
 [    5     8     0     8     2]
 [    3     6     4     0     3]
 [    2     9     7     6     0]]


array([[ 0, 12, 10,  6,  7],
       [ 3,  0,  5,  1,  4],
       [ 4,  8,  0,  8,  2],
       [ 3,  6,  4,  0,  3],
       [ 2,  9,  7,  6,  0]])

In [25]:
## ваш код
